name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Updated Firebase and other packages to resolve dependency conflicts
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0
  firebase_analytics: ^11.0.0
  firebase_ai: ^2.3.0 # Replaced discontinued firebase_vertexai
  firebase_app_check: ^0.3.0
  google_sign_in: ^6.3.0

  jitsi_meet_flutter_sdk: ^11.4.0
  go_router: ^14.8.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.0
  intl: ^0.19.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
