name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Downgraded Firebase packages to a compatible set based on firebase_vertexai's requirements
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  firebase_vertexai: ^0.1.0+1 # The package constraining our versions
  google_sign_in: ^6.2.1

  jitsi_meet_flutter_sdk: ^0.2.0
  go_router: ^14.1.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.0
  intl: ^0.19.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
