
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '           'see https://github.com/firebase/flutterfire/blob/master/packages/firebase_core/firebase_core/example/lib/main.dart',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdk-AAQoQoMGLWZckQLpfVH3O1FJKwVc',
    appId: '1:899792783636:web:c01989eb7f28b2dc631a01',
    messagingSenderId: '899792783636',
    projectId: 'unitylink-flutter-app',
    authDomain: 'unitylink-flutter-app.firebaseapp.com',
    storageBucket: 'unitylink-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: 'your_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'unitylink-flutter-app',
    storageBucket: 'unitylink-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: 'your_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'unitylink-flutter-app',
    storageBucket: 'unitylink-flutter-app.firebasestorage.app',
    iosClientId: 'your_ios_client_id',
    iosBundleId: 'your_ios_bundle_id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: 'your_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'unitylink-flutter-app',
    storageBucket: 'unitylink-flutter-app.firebasestorage.app',
    iosClientId: 'your_ios_client_id',
    iosBundleId: 'your_ios_bundle_id',
  );

    static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your_api_key',
    appId: 'your_app_id',
    messagingSenderId: 'your_messaging_sender_id',
    projectId: 'unitylink-flutter-app',
    authDomain: 'unitylink-flutter-app.firebaseapp.com',
    storageBucket: 'unitylink-flutter-app.firebasestorage.app',
  );

}
